export const AZERBAIJAN_LOCATIONS = [
    { name: "Bakı", region: "Bakı şəhəri" },
    { name: "Xırdalan", region: "Abşeron" },
    { name: "Abşeron", region: "Abşeron" },
    { name: "Xızı", region: "Abşeron" },
    { name: "Gəncə", region: "Gəncə-Daşkəsən" },
    { name: "Daşkəsən", region: "Gəncə-Daşkəsən" },
    { name: "Goranboy", region: "Gəncə-Daşkəsən" },
    { name: "Göygöl", region: "Gəncə-Daşkəsən" },
    { name: "Ağstafa", region: "Qazax-Tovuz" },
    { name: "Gədəbəy", region: "Qazax-Tovuz" },
    { name: "Qazax", region: "Qazax-Tovuz" },
    { name: "Şəmkir", region: "Qazax-Tovuz" },
    { name: "Tovuz", region: "Qazax-Tovuz" },
    { name: "Mingəçevir", region: "Şəki-Zaqatala" },
    { name: "Balakən", region: "Şəki-Zaqatala" },
    { name: "Qax", region: "Şəki-Zaqatala" },
    { name: "Qəbələ", region: "Şəki-Zaqatala" },
    { name: "Oğuz", region: "Şəki-Zaqatala" },
    { name: "Şəki", region: "Şəki-Zaqatala" },
    { name: "Zaqatala", region: "Şəki-Zaqatala" },
    { name: "Ağdaş", region: "Şirvan-Salyan" },
    { name: "Göyçay", region: "Şirvan-Salyan" },
    { name: "Hacıqabul", region: "Şirvan-Salyan" },
    { name: "Kürdəmir", region: "Şirvan-Salyan" },
    { name: "Salyan", region: "Şirvan-Salyan" },
    { name: "Şirvan", region: "Şirvan-Salyan" },
    { name: "Ucar", region: "Şirvan-Salyan" },
    { name: "Yevlax", region: "Şirvan-Salyan" },
    { name: "Zərdab", region: "Şirvan-Salyan" },
    { name: "Ağcabədi", region: "Qarabağ" },
    { name: "Ağdam", region: "Qarabağ" },
    { name: "Ağdərə", region: "Qarabağ" },
    { name: "Bərdə", region: "Qarabağ" },
    { name: "Füzuli", region: "Qarabağ" },
    { name: "Xankəndi", region: "Qarabağ" },
    { name: "Xocavənd", region: "Qarabağ" },
    { name: "Kəlbəcər", region: "Qarabağ" },
    { name: "Laçın", region: "Qarabağ" },
    { name: "Qubadlı", region: "Qarabağ" },
    { name: "Şuşa", region: "Qarabağ" },
    { name: "Zəngilan", region: "Qarabağ" },
    { name: "Beyləqan", region: "Mil-Muğan" },
    { name: "Biləsuvar", region: "Mil-Muğan" },
    { name: "İmişli", region: "Mil-Muğan" },
    { name: "Saatlı", region: "Mil-Muğan" },
    { name: "Sabirabad", region: "Mil-Muğan" },
    { name: "Astara", region: "Lənkəran-Astara" },
    { name: "Cəlilabad", region: "Lənkəran-Astara" },
    { name: "Lerik", region: "Lənkəran-Astara" },
    { name: "Lənkəran", region: "Lənkəran-Astara" },
    { name: "Masallı", region: "Lənkəran-Astara" },
    { name: "Yardımlı", region: "Lənkəran-Astara" },
    { name: "Quba", region: "Quba-Xaçmaz" },
    { name: "Qusar", region: "Quba-Xaçmaz" },
    { name: "Xaçmaz", region: "Quba-Xaçmaz" },
    { name: "Şabran", region: "Quba-Xaçmaz" },
    { name: "Siyəzən", region: "Quba-Xaçmaz" },
    { name: "Naxçıvan", region: "Naxçıvan MR" },
    { name: "Babək", region: "Naxçıvan MR" },
    { name: "Culfa", region: "Naxçıvan MR" },
    { name: "Kəngərli", region: "Naxçıvan MR" },
    { name: "Ordubad", region: "Naxçıvan MR" },
    { name: "Sədərək", region: "Naxçıvan MR" },
    { name: "Şahbuz", region: "Naxçıvan MR" },
    { name: "Şərur", region: "Naxçıvan MR" },
    { name: "Sumqayıt", region: "Sumqayıt şəhəri" },
    { name: "Lənkəran şəhəri", region: "Lənkəran-Astara" },
    { name: "Naftalan", region: "Gəncə-Daşkəsən" },
];

export const AZERBAIJAN_REGIONS = [...new Set(AZERBAIJAN_LOCATIONS.map((location) => location.region))];
